[package]

name = "crusty_chip"
version = "0.1.0"
authors = [ "radiantstatue@gmail.com" ]
edition = "2021"

[dependencies]
rand = "0.8.5"
bit_utils = "0.1.1"

[workspace]
members = ["sfml"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = "thin"
