[package]

name = "crusty-chip-sfml"
version = "0.1.0"
authors = [ "radiantstatue@gmail.com" ]
edition = "2018"

[dependencies.crusty_chip]
path = "../"

[dependencies]
sfml = "0.15.1"
getopts = "0.2.21"
