[package]

name = "crusty-chip-sfml"
version = "0.1.0"
authors = [ "radiantstatue@gmail.com" ]
edition = "2021"

[dependencies.crusty_chip]
path = "../"

[dependencies]
egui-sfml = { git = "https://github.com/crumblingstatue/egui-sfml.git" }
getopts = "0.2.21"
